"""
checker/reporters/docx_reporter.py

Generates a Word (.docx) security report using python-docx.
Same sections as the PDF report: title, executive summary, methodology,
findings table, detailed findings, appendix.
"""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime, timezone
from io import BytesIO

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import Inches, Pt, RGBColor

# ---------------------------------------------------------------------------
# Color helpers
# ---------------------------------------------------------------------------

_SEVERITY_RGB = {
    "HIGH": RGBColor(0xEF, 0x44, 0x44),
    "MEDIUM": RGBColor(0xF9, 0x73, 0x16),
    "LOW": RGBColor(0xEA, 0xB3, 0x08),
    "INFO": RGBColor(0x3B, 0x82, 0xF6),
}

_HEADER_BG = "1E3A5F"  # dark blue hex (no #)
_NEEDS_FIX_BG = "FEE2E2"
_PASSES_BG = "DCFCE7"
_INCONCLUSIVE_BG = "FEF9C3"
_ROW_ALT = "F3F4F6"


def _set_cell_bg(cell, hex_color: str):
    """Apply background shading to a table cell."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


def _cell_text(cell, text: str, bold=False, color: RGBColor | None = None,
               font_size: int = 9, font_name: str = "Calibri"):
    para = cell.paragraphs[0]
    run = para.runs[0] if para.runs else para.add_run()
    run.text = text
    run.bold = bold
    run.font.size = Pt(font_size)
    run.font.name = font_name
    if color:
        run.font.color.rgb = color


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def generate_docx(scan: dict, results: list[dict]) -> bytes:
    doc = Document()

    # Page margins
    for section in doc.sections:
        section.left_margin = Inches(0.9)
        section.right_margin = Inches(0.9)
        section.top_margin = Inches(0.8)
        section.bottom_margin = Inches(0.8)

    findings = [r for r in results if r.get("verdict") == "NEEDS_FIX"]
    passes = [r for r in results if r.get("verdict") == "PASSES"]
    inconclusive = [r for r in results if r.get("verdict") == "INCONCLUSIVE"]

    _add_title(doc, scan)
    _add_executive_summary(doc, scan, findings, passes, inconclusive)
    doc.add_page_break()
    _add_methodology(doc)
    doc.add_page_break()
    _add_findings_table(doc, findings)
    doc.add_page_break()
    _add_detailed_findings(doc, findings)
    if passes:
        doc.add_page_break()
        _add_appendix(doc, passes)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def _add_title(doc: Document, scan: dict):
    h = doc.add_heading("Authorization Check Report", level=0)
    h.alignment = WD_ALIGN_PARAGRAPH.CENTER

    sub = doc.add_paragraph("BOLA / IDOR Security Assessment")
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.runs[0].font.size = Pt(13)
    sub.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    doc.add_paragraph()  # spacer

    meta = [
        ("Target URL", scan.get("target_url", "—")),
        ("Spec Source", (scan.get("spec_source") or "—").capitalize()),
        ("Scan ID", (scan.get("id") or "—")[:16] + "…"),
        ("Started", _fmt_dt(scan.get("started_at"))),
        ("Completed", _fmt_dt(scan.get("completed_at"))),
        ("Generated", _fmt_dt(datetime.now(timezone.utc).isoformat())),
    ]
    tbl = doc.add_table(rows=len(meta), cols=2)
    tbl.style = "Table Grid"
    for i, (label, value) in enumerate(meta):
        row = tbl.rows[i]
        _cell_text(row.cells[0], label, bold=True)
        _cell_text(row.cells[1], value)
        _set_cell_bg(row.cells[0], "F3F4F6")

    doc.add_paragraph()
    note = doc.add_paragraph(
        "⚠ This report was generated by an automated authorization checker "
        "for educational and authorised testing purposes only."
    )
    note.runs[0].font.size = Pt(8)
    note.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)


def _add_executive_summary(doc, scan, findings, passes, inconclusive):
    doc.add_heading("Executive Summary", level=1)
    total = len(findings) + len(passes) + len(inconclusive)
    p = doc.add_paragraph(
        f"The checker performed {total} authorization checks against "
        f"{scan.get('target_url', '—')}."
    )
    p.runs[0].font.size = Pt(10)

    doc.add_heading("Results by Verdict", level=2)
    verdict_rows = [
        ("NEEDS FIX", str(len(findings)), _NEEDS_FIX_BG),
        ("PASSES", str(len(passes)), _PASSES_BG),
        ("INCONCLUSIVE", str(len(inconclusive)), _INCONCLUSIVE_BG),
        ("TOTAL", str(total), "F3F4F6"),
    ]
    tbl = doc.add_table(rows=len(verdict_rows) + 1, cols=2)
    tbl.style = "Table Grid"
    _set_cell_bg(tbl.rows[0].cells[0], _HEADER_BG)
    _set_cell_bg(tbl.rows[0].cells[1], _HEADER_BG)
    _cell_text(tbl.rows[0].cells[0], "Verdict", bold=True,
               color=RGBColor(0xFF, 0xFF, 0xFF))
    _cell_text(tbl.rows[0].cells[1], "Count", bold=True,
               color=RGBColor(0xFF, 0xFF, 0xFF))
    for i, (label, count, bg) in enumerate(verdict_rows, 1):
        _set_cell_bg(tbl.rows[i].cells[0], bg)
        _set_cell_bg(tbl.rows[i].cells[1], bg)
        _cell_text(tbl.rows[i].cells[0], label, bold=(label == "TOTAL"))
        _cell_text(tbl.rows[i].cells[1], count, bold=(label == "TOTAL"))

    doc.add_paragraph()
    doc.add_heading("Findings by Severity", level=2)
    by_sev: dict[str, int] = defaultdict(int)
    for r in findings:
        by_sev[r.get("severity", "INFO")] += 1

    sev_tbl = doc.add_table(rows=5, cols=2)
    sev_tbl.style = "Table Grid"
    _set_cell_bg(sev_tbl.rows[0].cells[0], _HEADER_BG)
    _set_cell_bg(sev_tbl.rows[0].cells[1], _HEADER_BG)
    _cell_text(sev_tbl.rows[0].cells[0], "Severity", bold=True,
               color=RGBColor(0xFF, 0xFF, 0xFF))
    _cell_text(sev_tbl.rows[0].cells[1], "Count", bold=True,
               color=RGBColor(0xFF, 0xFF, 0xFF))
    for i, sev in enumerate(["HIGH", "MEDIUM", "LOW", "INFO"], 1):
        _cell_text(sev_tbl.rows[i].cells[0], sev, color=_SEVERITY_RGB.get(sev))
        _cell_text(sev_tbl.rows[i].cells[1], str(by_sev.get(sev, 0)))


def _add_methodology(doc):
    doc.add_heading("Methodology", level=1)
    doc.add_paragraph(
        "The checker implements 10 distinct authorization check modules targeting "
        "OWASP API Security Top 10 — API1:2023 (BOLA/IDOR). Each module is applied "
        "to every applicable endpoint discovered from the provided specification."
    ).runs[0].font.size = Pt(10)

    modules = [
        ("HorizontalBOLA", "User A's token accessing User B's resource IDs", "HIGH"),
        ("VerticalPrivilege", "Non-admin roles accessing admin-only endpoints", "HIGH"),
        ("MissingAuth", "Unauthenticated requests to protected endpoints", "HIGH"),
        ("MalformedAuth", "Invalid/empty/wrong-scheme auth tokens", "MEDIUM"),
        ("IDManipulation", "Boundary, negative, string, and adjacent ID fuzzing", "MEDIUM"),
        ("MassAssignment", "Injecting role/is_admin/privilege in request body", "HIGH"),
        ("MethodSubstitution", "Alternate HTTP verbs on defined routes", "LOW"),
        ("ResponseLeakage", "Denial responses checked for stack traces / leaked data", "MEDIUM"),
        ("CrossEndpointGraph", "IDs from one response probed on related endpoints", "HIGH"),
        ("QueryParamSubstitution", "?user_id= and ?admin= query params honored by server", "HIGH"),
    ]
    tbl = doc.add_table(rows=len(modules) + 1, cols=3)
    tbl.style = "Table Grid"
    for j, hdr in enumerate(["Module", "Description", "Severity"]):
        _set_cell_bg(tbl.rows[0].cells[j], _HEADER_BG)
        _cell_text(tbl.rows[0].cells[j], hdr, bold=True,
                   color=RGBColor(0xFF, 0xFF, 0xFF))
    for i, (name, desc, sev) in enumerate(modules, 1):
        bg = _ROW_ALT if i % 2 == 0 else "FFFFFF"
        _set_cell_bg(tbl.rows[i].cells[0], bg)
        _set_cell_bg(tbl.rows[i].cells[1], bg)
        _set_cell_bg(tbl.rows[i].cells[2], bg)
        _cell_text(tbl.rows[i].cells[0], name, bold=True, font_size=8)
        _cell_text(tbl.rows[i].cells[1], desc, font_size=8)
        _cell_text(tbl.rows[i].cells[2], sev,
                   color=_SEVERITY_RGB.get(sev), bold=True, font_size=8)


def _add_findings_table(doc, findings):
    doc.add_heading("Findings Overview", level=1)
    if not findings:
        doc.add_paragraph("✓ No authorization gaps found. All checks passed.")
        return
    doc.add_paragraph(f"{len(findings)} authorization gap(s) identified.")

    headers = ["#", "Severity", "Endpoint", "Method", "Module", "Status"]
    tbl = doc.add_table(rows=len(findings) + 1, cols=len(headers))
    tbl.style = "Table Grid"
    for j, hdr in enumerate(headers):
        _set_cell_bg(tbl.rows[0].cells[j], _HEADER_BG)
        _cell_text(tbl.rows[0].cells[j], hdr, bold=True,
                   color=RGBColor(0xFF, 0xFF, 0xFF), font_size=8)
    for i, r in enumerate(findings, 1):
        sev = r.get("severity", "INFO")
        bg = _ROW_ALT if i % 2 == 0 else "FFFFFF"
        vals = [
            str(i), sev,
            _truncate(r.get("endpoint", "—"), 38),
            r.get("method", "—"),
            r.get("module_name", "—"),
            str(r.get("actual_status", "—")),
        ]
        for j, val in enumerate(vals):
            _set_cell_bg(tbl.rows[i].cells[j], bg)
            color = _SEVERITY_RGB.get(sev) if j == 1 else None
            _cell_text(tbl.rows[i].cells[j], val,
                       bold=(j == 1), color=color, font_size=8)


def _add_detailed_findings(doc, findings):
    doc.add_heading("Detailed Findings", level=1)
    for i, r in enumerate(findings, 1):
        sev = r.get("severity", "INFO")
        h = doc.add_heading(
            f"Finding #{i} — {sev} — {r.get('module_name', '?')}", level=2
        )
        h.runs[0].font.color.rgb = _SEVERITY_RGB.get(sev, RGBColor(0x3B, 0x82, 0xF6))

        doc.add_paragraph(
            f"Endpoint: {r.get('method', '')} {r.get('endpoint', '')}"
        ).runs[0].bold = True
        doc.add_paragraph(
            f"Expected Status: {r.get('expected_status', '?')}   "
            f"Actual Status: {r.get('actual_status', '?')}"
        )

        # Payload
        payload = r.get("payload_json") or r.get("payload") or {}
        if isinstance(payload, str):
            try:
                payload = json.loads(payload)
            except Exception:
                pass
        if payload:
            doc.add_paragraph("Request Payload:").runs[0].bold = True
            code_p = doc.add_paragraph(json.dumps(payload, indent=2)[:500])
            code_p.runs[0].font.name = "Courier New"
            code_p.runs[0].font.size = Pt(8)

        # Response snippet
        resp = r.get("response_snippet", "")
        if resp:
            doc.add_paragraph("Response Snippet:").runs[0].bold = True
            code_p = doc.add_paragraph(resp[:400])
            code_p.runs[0].font.name = "Courier New"
            code_p.runs[0].font.size = Pt(8)

        # Evidence diff
        diff = r.get("evidence_diff", "")
        if diff:
            doc.add_paragraph("Evidence:").runs[0].bold = True
            code_p = doc.add_paragraph(diff[:300])
            code_p.runs[0].font.name = "Courier New"
            code_p.runs[0].font.size = Pt(8)

        # Remediation
        rem = r.get("remediation", "")
        if rem:
            rem_p = doc.add_paragraph(f"💡 Remediation: {rem}")
            rem_p.runs[0].font.size = Pt(9)
            rem_p.runs[0].font.color.rgb = RGBColor(0x78, 0x35, 0x00)

        doc.add_paragraph()  # spacer between findings


def _add_appendix(doc, passes):
    doc.add_heading("Appendix — Passing Checks", level=1)
    doc.add_paragraph(
        f"{len(passes)} check(s) confirmed correct authorization behavior."
    )
    tbl = doc.add_table(rows=min(len(passes), 100) + 1, cols=4)
    tbl.style = "Table Grid"
    for j, hdr in enumerate(["Endpoint", "Method", "Module", "Status"]):
        _set_cell_bg(tbl.rows[0].cells[j], _HEADER_BG)
        _cell_text(tbl.rows[0].cells[j], hdr, bold=True,
                   color=RGBColor(0xFF, 0xFF, 0xFF), font_size=8)
    for i, r in enumerate(passes[:100], 1):
        bg = _ROW_ALT if i % 2 == 0 else "FFFFFF"
        vals = [
            _truncate(r.get("endpoint", "—"), 45),
            r.get("method", "—"),
            r.get("module_name", "—"),
            str(r.get("actual_status", "—")),
        ]
        for j, val in enumerate(vals):
            _set_cell_bg(tbl.rows[i].cells[j], bg)
            _cell_text(tbl.rows[i].cells[j], val, font_size=8)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _fmt_dt(dt_str: str | None) -> str:
    if not dt_str:
        return "—"
    try:
        dt = datetime.fromisoformat(dt_str.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        return str(dt_str)


def _truncate(s: str, n: int) -> str:
    return s if len(s) <= n else s[:n - 1] + "…"
